### ISSUE TITLE
webpack bunding issue after node upgrade

### ISSUE THREAD

**Issue by Leigh-M** [cdegalitt/libxmljs2-xsd#13]
I have upgraded from node v12 to v14.18.0 on Ubuntu Linux (21.04)

Webpack is struggling to bundle this correctly - with a different error, it appears to succeed however when run:

```
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'indexOf' of undefined",
  "trace": [
    "TypeError: Cannot read property 'indexOf' of undefined",
    "    at Function.getFileName (webpack-internal:///./node_modules/bindings/bindings.js:178:16)",
    "    at bindings (webpack-internal:///./node_modules/bindings/bindings.js:82:48)",
    "    at eval (webpack-internal:///./node_modules/libxmljs2/lib/bindings.js:1:92)",
    "    at Object../node_modules/libxmljs2/lib/bindings.js (/var/task/index.js:786:1)",
    "    at __webpack_require__ (/var/task/index.js:1995:42)",
    "    at eval (webpack-internal:///./node_modules/libxmljs2/index.js:4:18)",
    "    at Object../node_modules/libxmljs2/index.js (/var/task/index.js:776:1)",
    "    at __webpack_require__ (/var/task/index.js:1995:42)",
    "    at eval (webpack-internal:///./node_modules/libxmljs2-xsd/index.js:7:16)",
    "    at Object../node_modules/libxmljs2-xsd/index.js (/var/task/index.js:766:1)"
  ]
}
```

Any suggestions to resolve much appreciated. Thanks

**Comment by Leigh-M** [comment]
@cdegalitt I assume the issues myself and others are seeing is due to using webpack to bundle. I think the approach used here to not double include libxmljs2:

 “libxmljs2 module is required by node-libxml-xsd.. this prevents depending on libxmljs2 twice which is not optimal..”

The bundlers are not aware or do not correctly handle this and we end up with missing the libxmljs2 lib from bundles when it is needed.


Is there a simple work-around to just re-include it for cases where bundling is required? (Most production projects) like an ‘includeLibXmlJs2’ flag we could pass to force its inclusion? Thanks

**Comment by Leigh-M** [comment]
For anyone else struggling with with a missing libxmljs2 module when webpack'ing this and deploying to a lambda.. this webpack config runs as expected:

webpack.config.js

```
const path = require('path');

module.exports = {
    resolve: {
        extensions: ['.js'],
        mainFields: ['main'],
        modules: [
            path.resolve(__dirname, 'node_modules')
        ]
    },
    externals: {
        'aws-sdk': 'aws-sdk'
    },
    stats: {
        warningsFilter: 'Critical dependency: the request of a dependency is an expression'
    },
    optimization: {
        minimize: false
    },
    target: 'node',
    devtool: 'source-map',
    mode: 'development',
    entry: {
        someHandler1: './src/handlers/someHander1/index.js',
        someHandler2: './src/handlers/someHandler2/index.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name]/index.js',
        libraryTarget: 'commonjs'
    }
};
```
